export const UKRAINIAN_REGIONS = [
	'Cherkasy Oblast',
	'Chernihiv Oblast',
	'Chernivtsi Oblast',
	'Dnipropetrovsk Oblast',
	'Donetsk Oblast',
	'Ivano-Frankivsk Oblast',
	'Kharkiv Oblast',
	'Kherson Oblast',
	'Khmelnytskyi Oblast',
	'Kirovohrad Oblast',
	'Kyiv Oblast',
	'Luhansk Oblast',
	'Lviv Oblast',
	'Mykolaiv Oblast',
	'Odesa Oblast',
	'Poltava Oblast',
	'Rivne Oblast',
	'Sumy Oblast',
	'Ternopil Oblast',
	'Vinnytsia Oblast',
	'Volyn Oblast',
	'Zakarpattia Oblast',
	'Zaporizhzhia Oblast',
	'Zhytomyr Oblast'
];
